---
title: "Coursework"
format: html
engine: knitr
--- 
```{css}
#| echo: false
p, li {  
  text-align: justify;  
}  
```

Please find below a list of the projects I completed within the scope of my studies at SciencesPo : 

* [Microeconomics Paper on Game Theory applied to the Italian "Superbonus" policy](./Microeconomics_project.html) : This study examines how European governments use off-balance sheet fiscal tools, like Italy’s “Superbonus,” to hide public debt and evade EU fiscal rules. Using a game-theoretic model, we show that strict sanctions and weak enforcement can encourage even responsible governments to conceal debt. We also find that proportional penalties make high-debt countries more likely to cooperate on reducing debt than low-debt countries. This study argues for more comprehensive fiscal rules that account for hidden liabilities, not just official debt figures.
* [Macroeconomics Presentation on the DSGE model proposed by Frank Smets and Raf Wouters for the Euro Area](./Macroeconomics_project.html) : This presentation explains how Frank Smets and Raf Wouters, in the early 2000s, introduced a new way to estimate DSGE (Dynamic Stochastic General Equilibrium) models using Bayesian methods. It walks through the main statistical techniques they used, summarizes their key results, and discusses some of the limitations that were pointed out in later works. 
