---
title: "Projects"
--- 

Here is my latest personal project :
*

Please find below a list of the projects I completed before joining SciencesPo : 

* [Master Thesis on Ethnicity-related discrepancies in access to medication and service utilization amongst Medicare beneficiaries](./Master_Thesis.html) : This study uses the Medicare Current Beneficiary Survey(MCBS) Public Use Files(PUF) for 2013 and 2020 and investigates differences in access to medication across different ethnic groups using chi-square tests and multiple variable logistic regressions, adjusting for age, gender, education, starting health status (including chronic conditions) and type of health insurance coverage. **This project was done on Stata**
* [Group project on identifying key drivers of financial recession in the US](./KUBS_Recession.html) : This group project consists in identifying major indicators associated with financial recessions in the US, using data from the Federal reserve bank in Saint Louis. To do so we rely on a multiple variable logistic regression modeling the probability of a recession taking place as a function of several economic indicators that have been grouped in separate categories using two different methods (VIF and PCA analysis). To evaluate the relevance of each of the aforementioned grouping method used, we look at ROC curves obtained for each of them and conclude that the PCA method tends to perform better in this situation. **This project was done on Python**
